name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov
      - name: Install Composer dependencies
        run: cd backend && composer install
      - name: Run PHPUnit tests with coverage
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: cd backend && vendor/bin/phpunit --coverage-text

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Build frontend
        run: cd frontend && npm run build